# -*- coding: utf-8 -*-
"""Aula27Abril.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YoM656KEdQTDbPU9H6_7cj8KhIbfGco

# Manipulção de Textos em Python
"""

# @title Descobrindo quantas letras há na palavra

jedi = 'Luke Skywalker'

letras = len(jedi)

print(letras)

primeiraletra = jedi[0]  # Escolhendo elemento 0
print(primeiraletra)

ultimaletra = jedi[13]  # Escolhendi elemento 13
print(ultimaletra)

# Outra forma mais simples

palavra = 'Eu namoro uma mina linda'
print(len(palavra))

"""# Fatiamento das Palavras

Fatiar uma plavra é selecionar quais caracteres

serão escolhidos e usados.

Usa-se os colchetes [  ] e dentro os indices dos

elementos da palavra que queremos usar.
"""

# Exemplo de fatiamento de uma palavra

nome = jedi [0:4]
print(nome)    # Exibir somente a primeira palavra

# Exemplo de fatiamento com índice negativo

sobrenome = jedi[-10:]
print(sobrenome)

# Um outro  exemplo de fatiamento

comeco = jedi[:4]
print(comeco)

"""# Operadores relacionais"""

# @title Exercícos com operadores relacionais

a = 1 # a recebe valor 1
b = 5 # b recebe valor 5
c = 2 # c recebe valor 2
d = 1 # d recebe valor 1

# Teste de igualdade

a == b # a é igual a b?

b >= a # b é maior ou igual a a?

c <= d # c é menor ou igual a d?

# Teste de desigualdade

d != a # d é diferente de a?

d != b # d é diferente de b?

# @title  Operadores relacionais e variáveis

nota = 7   # Valor da nota

media = 7  # Valor da média

aprovada = nota >= media # Criterio de aprovação
print (aprovada)  # O resultado do testo

# Exemplo de códiogo com operadores lógico and

num1 = 7
num2 = 4

num1 > 3 and num2 < 8  # Operação lógica com and

# Exemplo de operação lógica not

print('not True =', not True)
print ('\nnot False', not False)  # O not é chamado de inversor

""" # Exercíco de aprovação do emprestimo

 Condição de aprovação: salario > 100 e idade > 18

 Considerar salario igual a R$1000,00 e idade igual a 20 anos
"""

# Exemplo de aprovação de empréstimo
# Condição de aprovação: salário > 1000 e idade > 18

salario = 100
idade = 20

condicao = (salario >= 1000 and idade >= 18)

print('O empréstimo foi aprovado?', condicao)

"""Agora salário é iguak a R$2000,00 e idade igual a 20 anos"""

# Exemplo de aprovação de empréstimo
# Condição de aprovação: salário > 1000 e idade > 18

salario = 2000
idade = 20

condicao = (salario >= 1000 and idade >= 18)

print('O empréstimo foi aprovado?', condicao)

"""# Formantando a saída do texto"""

# Exemplo de formação de texto

tutor =  'Obiwan Kenobi'

print(tutor)
print(jedi)

print(f'\nO professor do {jedi} é o {tutor}')

# Exemplo de formatação de número

x = 23
y = 34.45

z = x * y

print(f'O resultado de {x} * {y} é igual a {x*y:.1f}')

"""#Estruturas de decisão em Python"""

# Exemplo de um condicional simples
idade = 17
if idade >= 18:
    print('Você é maior de idade!')
print('Você é menor de idade!')

# Exemplo de estrutura de decisão simples

age = 19
print('Hora do teste...\n')

if age >= 18:
    print('Você é maior de idade')
    print('Essa linha também será impressa...')

print('\nFora do bloco do if')

# Exemplo de estrutura de decisõ simples
tempo = int(input('Quantos anos tem o seu carro?'))
if tempo <= 3:
    print('Seu carro é novo!')
if tempo > 3:
    print('Seu carro é velho!')
print('\nFim do programa...')

# Exemplo de estrutura de decisõ composta
tempo = int(input('Quantos anos tem o seu carro?'))
if tempo <= 3:
    print('Seu carro é novo!')
else:
    print('Seu carro é velho!')
print('\nFim do programa...')

"""# Exercíco 1

Crie um programa que pede a idade do usuário e

avalia de é maior ou igual a 18 anos.

Exiba a mensagem "Maior de idade" ou

"Menor de idade" de acordo com a condição.
"""

usuario = int(input('Qual sua idade?'))
if usuario >= 18:
    print('Você é maior de idade')
else:
    print('Você é menor de idade')

"""# Exercíco 2

Crie um programa que pede duas notas ao usuário e

calcula a média das notas

se a média for maior ou igual a 7 exibia a

mensagem "Aluno aprovado" e a mensagem "Aluno reprovado"

se for ao contrario
"""

nota1 = int(input('Digite a sua nota'))
nota2 = int(input('Digite a sua nota'))
notafinal = nota1 + nota2
resultado = notafinal/2

if resultado >= 7:
    print('\nVocê foi aprovado')
else:
    print('\nVocê foi reprovado')

# @title Exemplo de estrutura de decisão aninhada

print('\nInicio do programa...')
minutos = int(input('\nQuantos minutos você usou esse mês?'))
if minutos < 200:
    preco = 0.20
else:
    if minutos < 400:
        preco = 0.18
    else:
        preco = 0.15
print(f'\nVocê vai pagar este mês: R${minutos * preco:6.2f}')
print('\nFim do programa...')

# @title Exemplo de código com várias categorias

print('\nInicio do programa...')
 categoria = int(input('\nQual a categoria do seu produto?'))
 if categoria == 1:
    preco = 10
else:
    if categoria == 2:
        preco = 18
    else:
            if categoria == 3:
                preco = 23
            else:
                    if categoria == 4:
                        preco = 26
                    else:
                        if categoria == 5:
                            preco = 31
                        else:
                            print('Categoria inválida!')
                            preco = 0
print(f'O preço do produto é R$ {preco: .2f}')
print('\nFim do programa...')

print('\nInicio do programa...')
categoria = int(input('\nQual a categoria do seu produto?'))
if categoria == 1:
    preco = 10
elif categoria == 2:
    preco = 18
elif categoria == 3:
    preco = 23
elif categoria == 4:
    preco = 26
elif categoria == 5:
    preco = 31
else:
    print('Categoria inválida!')
    preco = 0
print(f'O preço do produto é R$ {preco: .2f}')
print('\nFim do programa...')

n1 = float(input('\nDigite a sua nota'))
n2 = float(input('\nDigite  sua nota'))
m = (n1 + n2)/2
if m >=7:
    print('\nAprovado')
elif m >=5:
    print('\nRecuperação')
elif m <5:
    print('\nReprovado')

print('\nInicio do programa..')
nota3 = float(input('Digite sua nota'))
print()
nota4 = float(input('Digite a sua nota'))
m = (nota3 + nota4)/2
if m  >=7:
    print(f'Você foi aprovado com média {m:.1f}')
elif m >= 5:
    print(f' Você está em recuperação com média {m:.1f}')
else:
    print(f'Você está reprovado com média {m:.1f}')

print('\nFim do Programa')

numeroqualquer = float(input('Digite um número'))
if numeroqualquer >0:
    print('O seu número é positivo')
elif numeroqualquer <0:
    print('Seu número é negativo')
else:
    print('Seu número é nulo')

horario =int(input('Digite um horário\n'))
if horario >=6 and horario <=12:
    print('Boa Manhã')
elif horario >=12 and horario <=18:
    print('Boa Tarde')
elif horario >=18 and horario <=23:
    print('Boa Noite')
else:
    print('Boa Madrugada')

"""# Exercíco

Crie um programa que testa se um número inteiro é par ou impar
"""

naruto = int(input('Digite algum número'))
if naruto % 2 == 0:
    print('O seu número é par')
else:
    print('O seu número é impar')

"""# Estrutura de Repetição em Python"""

# @title Um exemplo motivador

valor_total_compra = 0 # cria e inicia a variável
valor_feijao = 5.5
valor_arroz = 4
valor_macarrao = 2

produto = input('Digite o código do produto: ')

if produto == 'feijao':
    valor_total_compra = valor_total_compra + valor_feijao #valor_total_compra += valor_feijao (outra forma de fazer esse código)
elif produto == 'arroz':
    valor_total_compra += valor_arroz
elif produto == 'macarrao':
    valor_total_compra += valor_macarrao

print(f'\nO valor total compra é R${valor_total_compra}.')

"""# Entendendo o laço for"""

# Exemplo de repetição com for

for contador in range(10):
    print('Boa tarde')

# @title A identação é importante

print('Inicio do programa...\n')

for n in range(10):
    print('No bloco')
    print('Oi')

print('Fora do Bloco')

"""# Entendendo o laço for"""

# Exemplo de iteração pelo laço
for contagem in range(10):
    texto=str(contagem)
    print(f'O valor de contagem é {texto}')

# Exemplo da iteração com o for

frase = 'Olá Senai Suiço!'
for letra in frase:
    print(letra)

# Outro exemplo de iteração pelo laço for

frase = 'Obiwan Kenobi'
for letra in frase:
    print(letra)

# Exemplo de itineração
for c in range(49):
    print(c)

for y in range(1, 20, 3):
    print(y)

for a in range(20):
    print(a)

# Exemplo de laço for e como o contador é atualizado

print('Inicio do progrfama de repetição...\n')

texto = input('Qual a mensagem?') # Solicita a mensagem e armazena variavel texto
quantidade = int(input('Quantas vezes devo repetir a mensagem? '))
for n in range(quantidade):
    mensagem = texto + ' ' + str(n) # Converte para texto e concatena
    print(mensagem) # Exibe a mensagem
print('\nFim do programa...')

# @title Exemplo de contador crescente

print('Inicio do contador...\n')
for z in range(50):
    print(z)

# @title Exemplo de contador decrescente

print('Inicio do contador...\n')
for m in range(100, -1, -1):
    print(m)

"""# Corrigindo o programa do mercado"""

# O programa do mercado corrigido

print('Inicio... Bem-Vindo ao nosso mercado!\n')

# Definindo as variaveis
valortotalcompra = 0
valorfeijao = 5.5
valorarroz = 4
valormacarrao = 2
l = int(input('Quantos produtos vc vai comprar?'))

for qualquercoisa in range(l):
    mercadoria = input('Digite um produto:')

    if mercadoria =='feijao':
        valortotalcompra += valorfeijao
    elif mercadoria == 'arroz':
        valortotalcompra += valorarroz
    elif mercadoria == 'macarrao':
        valortotalcompra += valormacarrao

print(f'O valor a ser pago R${valortotalcompra}.\n')
print('Volte sempre...\n')

print('\nFim...')

# @title Entendendo o laço While

print('Inicio do programa..\n')

controle = 1 # Vairável de controle de laço
while controle <10: # Uso do laço While
    print(controle) # Exibe a variavel
    controle += 1 # Incrementa a variável de uma unidade

print('\nFim do Programa...')

# Um outro exemplo de laço while

print('Inicio do programa...\n')

contador = 1
while contador <=15:
    if contador %2 == 0:
        print(contador)
    contador +=1

print('\nFim do programa...')

# Contador crescente em while

print('Inicio do programa...\n')

f = 0
while f <=50:
    print(f)
    f += 1

"""# Exemplo de contagem decrescente com while"""

# Um programa que conta

teste = 100
while teste > -1:
    print(teste)
    teste -= 1

"""# Interrompendo um laço



"""

# Exemplo de interrupção de um laço

for j in range(10):
    if j % 2 != 0: # Essa condição é verdadeira para números impares
        print(j)
        break

"""# Um exemplo de interrupção com continue"""

# Exemplo de uso do continue

for x in range(20):
    if x == 1 or x == 8:
        continue
    print(x)