# -*- coding: utf-8 -*-
"""Aula18Maio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRUuw2oTJr4o2IklfERCbEUeiwjnzeJH

# FUNÇÕES EM PYTHON

Funções dentro de funções
"""

# @title Exemplo de função dentro de função - Média

lista = [4,87,123,12,4,28]
def media(lista):
    return sum(lista)/len(lista) # Sum é a função de soma
print(media(lista))

def somar(lst):   # Assinatura da função
    total = 0    # Declarando uma variável que armazena o total da lista
    for e in lst:  # Percorrer os elementos da lista
        total += e  # Adiciona e a variável total
    return total  # No fim da lista, obtemos a soma

def media(lista):
    resultado = somar(lista)/len(lista)  # Resultado terá a média da lista
    return resultado
lista = [4,87,13,1098,4,28]
media(lista)

"""Outro exemplo de função dentro de função: par ou ímpar"""

# @title Exemplo de função - épar

def ehpar(wii):  # Assinatura da função
    return wii % 2 == 0  # Retorno da função: True se for par e False se for ímpar
ehpar(45)

# @title Exemplo de fução dentro de função - par ou ímpar

def par_ou_impar(p):
    if ehpar(p):
        return 'É par!'
    else:
        return 'É impar!'

par_ou_impar(123)

"""# ESCOPO E TEMPO DE VIDA DAS VARIÁVEIS"""

# @title Escopo e tempo de vida - Exemplos

# Programa que cria a função teste

def teste():
    xis = 300
    print(f'Na função teste xis vale {xis}\n')
    print(f'Na função teste numero vale {numero}')

teste()

# Prograa principal

numero =  97
print(f'No programa princilpal a minha variável número vale {numero}\n')
print()
print(f'No programa principal xis vale {xis}')

"""# Ajuda interativa - Interactive Help"""

help()



"""# Documentação da função - Docstrings

Docstrings são a forma de adicionar como ou o que a função faz para um usuário

Eles são acessados através do comando help(nome_da_função)

Como criar a sua docstring da sua função?

Use três aspas dulpas (2x) logo depois da definição da função



```
# Isto está formatado como código
def nomedafuncao(nomedoparamento):
    '''
    -> Essa função faz tal coisa...
    :param: nomedoparametro usado para etc...
    :param: .....
    :param: ...
    '''
Corpo da função vem aqui
```


"""

# @title Uma função Docstring

def exemplodoc(nome,data):
    """
    -> Essa função mostra como criar um
    - minihelp da função
    :param nome: nome de exemplo
    :param data: data de exemplo
    """
    print(f'O nome fornecido foi {nome} e a data foi {data}\n')

exemplodoc('Carlos','18/05/2024')

help(exemplodoc)

"""# Módulos em Python

Vamos importar o módulo de função matemáticas - math

E verificar quais funções ele contém.

Use o comando dir(nome_do_modulo)
"""

import math
print(math.sin(math.pi/2))

import math
# Esse jeito de importat traz todas as funções disponíveis em math

dir(math)  # Para ver todas as funções existentes no módulo math
# len(dir(math))

# @title Excemplo de importação seletiva em um módulo

# from random import random  # Importar do módulo random a função

from random import random as aleatorio

for i in range(5):
    print(aleatorio())

# @title Outro exemplo de importação seletiva em um módulo

from platform import platform
from platform import machine

print(platform())
print(machine())