# -*- coding: utf-8 -*-
"""Aula20abril.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5jK3lOR-G1ypYHbiJyDa7IpGPwN4OEJ

# Curso de Programa em Python
"""

print ("Olá SENAI") # Meu primeiro programa

print (8*5)

print (12375.8) # o primeiro número fracionado - float

print ("leandro" ,"Marcia", sep="*******")

"""# Operações em Python"""

# @title Adição

print(8+10) # Exemplo de adição

print(9+20.5) # exemplo de adição inteiro e float

# @title Subtração

print(84-90) # Exemplo de subtração entre iteiros

print(55.86-29.32) # Exemçlo de subtração entre inteiro e float

# @title Multiplicação

print(7928.23*2) # Exemplo de multiplicação entre inteiro e float

# @title Divisão

print(100/10) # Exemplo de divisão entre float
print(20/5.5) # Exemplo de divisão entre float

print(100 // 5.0) # Exemplo de divisão entre inteiro e float

print(100//5) # Exemplo de divisão inteira

# @title Exponenciação

print(4**4) # Exemplo de exponenciação entre inteiro

print(3**2.5) # Exemplo de exponenciação entre inteiro e float

# @title Módulo

print(12 % 5) # Exemplo de Módulo

print(12 % 2 ) # Exemplo de operação de módulo

print(12 % 4.5) # Exemplo de módulo entre inteiro e float

"""# Exercício 1
Crie um programa para receber dois valores e em seguida exiba a soma deles
"""

# Programa para receber dois valores e exibir a soma

valor_1 = 550 #primeira variável
valor_2 = 230 #segunda variável

soma = (valor_1 + valor_2)

print('O resultado de valor_1 e valor_2 é', soma)

"""# Exercício 2

Crie um programa para receber dois valores e em seguida, exiba o valor da diferença entre eles
"""

# Programa para receber dois valores, e exibir a diferença

valor_1 = 60
valor_2 = 30

sub = (valor_1 - valor_2)
print('A diferença entre valor_1 e valor_2 é', sub)

""" # Exercíco 3
 Crie um programa para receber dois valores e em seguida, exiba o produto entre eles
"""

# Programa para receber dois valores, e exiba o produto

 valor_1 = 5
 valor_2 = 34

 mul = (valor_1 * valor_2)
 print('O produto entre valor1 e valor2 é', mul)

"""# Exercíco 4
Crie um programa para receber dois valores e em seguida, exiba o quociente entre eles
"""

# Programa para exibir o quociente entre eles

 valor1 = 121
 valor2 = 11

 div = (valor1 / valor2)
 print('O quociente de valor1 e valor2 é', div)

"""# Exercíco 5
Crie um programa para receber dois valores e em seguida, exiba o resto da divisão entre eles
"""

# Programa para exibir o resto da divisão

valor_1 = 38
valor_2 = 3

porc = (valor_1 % valor_2)
print('O resto da divisão é', porc)

"""# Exercíco 6
Crie um programa para receber dois valores e em seguida, exiba o quadrado entre eles
"""

# Programa que exibe o quadrado

valor1 = 56
valor2 = 3

quad= (valor1 ** valor2)
print('O quadrado é', quad)

"""# Exercício 7
Crie um programa para fazer a raiz quadrada de um número utilizando a biblioteca math
"""

# Programa que exibe a raiz quadrada de um número

valor = float(input('Digite um número'))
print('A raíz quadrada é',valor **(1/2))

# Exemplo de biblioteca math

import math  # Importar a biblioteca

#número = 50 # Criando a variável

número = float(input('Digite um número'))

raizquadrada = math.sqrt(número)
print('A raíz quadrada é', raizquadrada)

"""#Exercíco de 4 número"""

#Programa dos 4 números

print('Inicio do programa...\n')

 #Entrada do programa
 A = float(input('Digite o primeiro número:'))
 B = float(input('Digite o primeiro número:'))
 C = float(input('Digite o primeiro número:'))
 D = float(input('Digite o primeiro número:'))

 #Processamento
 X = A*B
 Y = C*D

 resultado = X - Y

 # Saida
 print('\n O resultado de X - Y é', resultado)

 print('\nFim do programa...')

"""# Ordem dos operadores"""

# Exemplo de operação de módulo

print(9%6%2) # Esse operador tem ligação pelo lado esquerdo
#Executar da esquerda para a direita

# Exemplo de operação exponenciação

print(2**2**3) # Esse operador tem ligação do lado direito
#Executar da direita para a esquerda

"""# Identificando o tipo de dado

"""

#Exemplo de teste de tipo de dados

print('4 é considerado')
print(type(4))
print('\n 307 é considerado')
print(type(307))
print('\n187789.7 é considerado')
print(type(187789.7))
print('\n"Noel" é considerado')
print(type("Noel"))
print('\n"-307/" é considerado')
print(type("-307/"))
print('\n"SENAI" é considerado')
print(type("SENAI)"))

"""# Texto e seus segredos"""

# @title Descobrindo quantas letras há em uma palavra

palavra = 'O rato roeu a roupa do rei de roma'

len(palavra)

"""Descubra quantas letras tem em:

'Cadeia de caracteres'
'João tem 22 anos e R$ 78,98 no bolso'
"(aspas vazias)

"""

frase1 = 'Cadeia de caracteres'
frase2 = 'João tem 22 anos e R$78,98 no bolso'

print(len(frase1))
print(len(frase2))

namorada = input('')